//go:build ignore

// This file shows the structure of the generated config.go
// The actual config.go is generated by the builder tool and should not be committed.
// Copy this file to config.go and modify for local testing.

package config

// Global Settings
var (
	UUID  = "00000000-0000-0000-0000-000000000000"
	Debug = true
)

// Build Info
var (
	BuildOS   = "linux"
	BuildArch = "amd64"
)

// Egress Settings
var (
	EgressOrder       = []string{"http"}
	EgressFailover    = "failover"
	FailedThreshold   = 10
	BackoffDelay      = 5
	BackoffBase       = 1
)

// UI Client Settings
var (
	UIBaseURL      = "http://localhost:11111"
	UICheckinPath  = "/checkin"
	UIPollPath     = "/poll"
	UIPollInterval = 5
	UIHTTPTimeout  = 30
)

// HTTP Profile
var (
	HTTPCallbackHost      = "https://localhost:443"
	HTTPCallbackPort      = 443
	HTTPAesPsk            = ""
	HTTPKilldate          = "2099-12-31"
	HTTPInterval          = 10
	HTTPJitter            = 20
	HTTPPostUri           = "/data"
	HTTPGetUri            = "/news"
	HTTPQueryPathName     = "q"
	HTTPEncryptedExchange = true
	HTTPHeaders           = map[string]string{}
	HTTPProxyHost         = ""
	HTTPProxyPort         = 0
	HTTPProxyUser         = ""
	HTTPProxyPass         = ""
	HTTPProxyBypass       = false
)

// Websocket Profile
var (
	WebsocketCallbackHost      = ""
	WebsocketCallbackPort      = 0
	WebsocketAesPsk            = ""
	WebsocketKilldate          = ""
	WebsocketInterval          = 0
	WebsocketJitter            = 0
	WebsocketEndpoint          = ""
	WebsocketEncryptedExchange = true
	WebsocketDomainFront       = ""
	WebsocketTaskingType       = "Push"
	WebsocketUserAgent         = ""
)

// TCP Profile
var (
	TCPPort              = 0
	TCPAesPsk            = ""
	TCPKilldate          = ""
	TCPEncryptedExchange = true
)

// DNS Profile
var (
	DNSDomains            = []string{}
	DNSAesPsk             = ""
	DNSKilldate           = ""
	DNSInterval           = 0
	DNSJitter             = 0
	DNSServer             = ""
	DNSDomainRotation     = "fail-over"
	DNSFailoverThreshold  = 3
	DNSRecordType         = "TXT"
	DNSMaxQueryLength     = 253
	DNSMaxSubdomainLength = 63
	DNSEncryptedExchange  = true
)

// DynamicHTTP Profile
var (
	DynamicHTTPAesPsk            = ""
	DynamicHTTPKilldate          = ""
	DynamicHTTPInterval          = 0
	DynamicHTTPJitter            = 0
	DynamicHTTPEncryptedExchange = true
	DynamicHTTPRawC2Config       = ``
)

// HTTPx Profile
var (
	HTTPxCallbackDomains      = []string{}
	HTTPxAesPsk               = ""
	HTTPxKilldate             = ""
	HTTPxInterval             = 0
	HTTPxJitter               = 0
	HTTPxDomainRotationMethod = "fail-over"
	HTTPxFailoverThreshold    = 3
	HTTPxEncryptedExchange    = true
	HTTPxRawC2Config          = ``
)
